org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.4
archives_base_name=EnhancedQuarries
mod_version=1.7.1
maven_group=net.pitan76

# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=11.1.17

# https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_api_version=0.96.1+1.20.4
yarn_mappings=1.20.4+build.3

# https://files.minecraftforge.net/
forge_version=1.20.4-49.0.28

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=20.4.251

mcpitanlib_version=-1.20.4:4.0.1
#mcpitanlib_checker_version=1.0.4

# TechReborn / RebornCore (Fabric only)
reborncore_version=5.10.3
techreborn_version=5.10.3

# https://www.curseforge.com/minecraft/mc-mods/cloth-config
cloth_config_api_version=13.0.121

# Fabric only compat
modmenu_version=9.0.0
storagebox_fabric_file_id=5183616

fabricEnabled=true
forgeEnabled=true
neoforgeEnabled=true

changelog=Add support NeoForge and Forge
