dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    modCompileOnly "net.pitan76:mcpitanlib-common${rootProject.mcpitanlib_version}"
}

architectury {
    common("fabric", "forge", "neoforge")
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-common"
            version = rootProject.mod_version + "-SNAPSHOT"
            from components.java

            pom.withXml {
                def pomNode = asNode()
                pomNode.dependencies.'*'.findAll {
                    def groupId = it.groupId.text()
                    def artifactId = it.artifactId.text()

                    (groupId == 'net.pitan76' && artifactId.startsWith('mcpitanlib-')) ||
                            (groupId == 'net.fabricmc.fabric-api')
                }.each() {
                    it.parent().remove(it)
                    print("Removed dependency: ${it.groupId.text()}:${it.artifactId.text()}\n")
                }
            }
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/PTOM76/maven")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
